@echo off
cd /d "c:\Users\Rodri\Downloads\FaceDetectorApp\FaceDetectorApp"
echo Iniciando git...
git init
echo Adicionando arquivos...
git add .
echo Fazendo commit...
git commit -m "Add video recording: 1h duration, H.264 480p, auto storage cleanup at 30%% threshold"
echo Renomeando branch...
git branch -M main
echo Adicionando remote...
git remote add origin https://github.com/rodrigoctoledo/app-face-app.git
echo Fazendo push...
git push -u origin main
pause
